version: '3.8'

services:
  smppinterface:
    image: dk-reg.mas:5000/beacon:23sep2025
    container_name: smppinterface
    volumes:
      - './config/kafka2es.properties:/kafka2es.properties'
      - './logs:/opt/jboss/wildfly/logs'
    ports:
      - "2775:2775"
      - '5081:8081'
      - "5080:8080"
    environment:
      - id=1
      - _JAVA_OPTIONS=-Xmx256m -Xms256m
      - module=smppinterface
      - profile=do4
      - modvalue=0,1,2,3
      - cluster.names=trans,bulk,otp,intl
      - concat.redis.index=0,1,2,3
      - cluster=trans,bulk,otp,intl
      - hostname=10.122.0.2
      - segment=chk3s
      - handovergw=unitia
    command: >
      sh -c "java
      -Dcommon.property.file.location=/global.properties
      -Dkafka.2.elasticsearch.config.file=/kafka2es.properties
      -Dlog4j.configurationFile=file:/log4j2-common.xml
      -Djavax.xml.bind.JAXBContextFactory=com.sun.xml.bind.v2.ContextFactory
      -Djavax.xml.bind.JAXBContext=com.sun.xml.bind.v2.ContextFactory
      -Dreactor.schedulers.defaultBoundedElasticSize=50
      -Dreactor.schedulers.defaultBoundedElasticQueueSize=1000
      -jar /mainmodule-1.0-executable.jar > /dev/null 2>&1"  
    networks:
      - interface
networks:
  interface:
    external: true
